# Generated by Django 3.2 on 2021-04-14 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='texte',
            new_name='texto',
        ),
        migrations.AlterField(
            model_name='blog',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='media/blog-imagens', verbose_name='Imagem'),
        ),
    ]
