# Generated by Django 3.2 on 2021-04-14 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210414_0114'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='media/blog-imagens/autores', verbose_name='Imagem')),
                ('likes', models.IntegerField(default=0)),
                ('artigos', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.CharField(max_length=200, verbose_name='Pergunta')),
                ('resposta', models.TextField(verbose_name='Resposta')),
            ],
        ),
        migrations.CreateModel(
            name='Frase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frase', models.CharField(max_length=200, verbose_name='Frase')),
            ],
        ),
    ]
