# Generated by Django 3.2 on 2021-04-15 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_autore_faq_frase'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='biografia',
            field=models.CharField(default=0, max_length=200, verbose_name='Biografia'),
        ),
    ]
