# Generated by Django 3.2 on 2021-04-15 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blog_biografia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='biografia',
            field=models.CharField(default='não consta', max_length=200, verbose_name='Biografia'),
        ),
    ]
